name: Build & Release Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    uses: Flower7C3/minecraft-addon-workflows/.github/workflows/build-and-release.yml@main
    with:
      project_name: "Just clock"
      has_test_workflow: false
      total_blocks: false
    secrets: inherit